   [build]
     publish = "dist"
     command = "npm run build"

   [[headers]]
     for = "/*"
     [headers.values]
       Content-Type = "text/javascript"

   [[redirects]]
     from = "/*"
     to = "/index.html"
     status = 200