app = "atc-01554128937-wwnj3q"
primary_region = "ewr"  # Choose a region closest to you

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[deploy]
   release_command = "npx prisma generate && npx prisma db push --schema=./prisma/schema.prisma --accept-data-loss"